export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";
export const GET_CONTENT_SUCCESS = "GET_CONTENT_SUCCESS";

export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_COINS_SUCCESS="GET_COINS_SUCCESS";
export const GET_WEB_DESIGN_PROJECTS_SUCCESS="GET_WEB_DESIGN_PROJECTS_SUCCESS";
export const SET_LANGUAGE="SET_LANGUAGE";